In [ ]:
#                                       Session SQl2 Assignment

# Read the following data set: 
# https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data 
# Task: 
# 1.  Create an sqlalchemy engine using a sample from the data set 
# 2.  Write two basic update queries 
# 3.  Write two delete queries 
# 4.  Write two filter queries 
# 5.  Write two function queries 
 


#******************************************************************************************************
#                         Task 1 :  Reading the DataSet and Creating sqlalchemy engine using a sample of it
#
#******************************************************************************************************
#importing the packages and setting an alias pandas and all the sqlalchemy related functions 

import pandas as pd
import sqlalchemy as sqy
from sqlalchemy import  create_engine,Column,Integer,String,Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


#reading the dataSet 

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# List of Column Names from the Adultnames file
ColumnNames= ['age','workclass','fnlwgt','education','educationNum','maritalStatus','occupation','relationship','race','sex','capitalGain','capitalLoss','hoursperweek','nativeCountry','salperyear']

df.columns = ColumnNames

#printing the Data read
#print(df.head())

# Creating a sqlalchemy engine
engine = create_engine('sqlite:///:memory:', echo=False)
#print(sqy.__version__)

# Constructing the Base Class from declarative to create table from it 
Base = declarative_base() 

class Adult(Base):
    __tablename__ = 'adult'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    workclass = Column(String)
    fnlwgt = Column(Integer)
    education = Column(String)
    educationNum = Column(Integer)
    maritalStatus = Column(String)
    occupation = Column(String)
    relationship = Column(String)
    race = Column(String)
    sex = Column(String)
    capitalGain = Column(Integer)
    capitalLoss = Column(Integer)
    hoursperweek = Column(Integer)
    nativeCountry = Column(String)
    salperyear = Column(String)
   
    def __repr__(self):
        return "<Adult(age='%d', workclass='%s', fnlwgt='%d',education='%s', educationNum='%d',maritalStatus ='%s',occupation ='%s',relationship ='%s',race ='%s',sex ='%s',capitalGain ='%d',capitalLoss ='%d',hoursperweek ='%d',nativeCountry ='%s',salperyear ='%s')>" %(
    self.age, self.workclass,self.fnlwgt,self.education,self.educationNum,self.maritalStatus,self.occupation,self.relationship,self.race,self.sex,self.capitalGain,self.capitalLoss,self.hoursperweek,self.nativeCountry,self.salperyear)


# creating the Table in the Engine, i.e memory
Base.metadata.create_all(engine)

#binding the engine to the session 
SessionMaker = sessionmaker(bind=engine)

session = SessionMaker()

# adding the data in the session , by first converting first 5 records to dictionary and then accessing individiuallyusing addall to add multiple rows 

dict1 = (df.head().to_dict('index'))
for x in dict1.values():
    temp = Adult(**x)
    session.add(temp)
    
# Commit flushes all the new data in session to the Database in memmory 
session.commit()
    
print("Following are the records from the adult table in memory retrieved and printed :\n",'-'*80)    
# now retrieving the records from the session through query and printing 
for row in session.query(Adult).all():
    print(row)
    print('-'*80)


#******************************************************************************************************

In [ ]:
#******************************************************************************************************
#                         Task 2 :  To write two basic update Queries 
#
#******************************************************************************************************
#importing the packages and setting an alias pandas and all the sqlalchemy related functions 

import pandas as pd
import sqlalchemy as sqy
from sqlalchemy import  create_engine,Column,Integer,String,Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


#reading the dataSet 

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# List of Column Names from the Adultnames file
ColumnNames= ['age','workclass','fnlwgt','education','educationNum','maritalStatus','occupation','relationship','race','sex','capitalGain','capitalLoss','hoursperweek','nativeCountry','salperyear']

df.columns = ColumnNames

#printing the Data read
#print(df.head())

# Creating a sqlalchemy engine
engine = create_engine('sqlite:///:memory:', echo=False)
#print(sqy.__version__)

# Constructing the Base Class from declarative to create table from it 
Base = declarative_base() 

class Adult(Base):
    __tablename__ = 'adult'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    workclass = Column(String)
    fnlwgt = Column(Integer)
    education = Column(String)
    educationNum = Column(Integer)
    maritalStatus = Column(String)
    occupation = Column(String)
    relationship = Column(String)
    race = Column(String)
    sex = Column(String)
    capitalGain = Column(Integer)
    capitalLoss = Column(Integer)
    hoursperweek = Column(Integer)
    nativeCountry = Column(String)
    salperyear = Column(String)
   
    def __repr__(self):
        return "<Adult(age='%d', workclass='%s', fnlwgt='%d',education='%s', educationNum='%d',maritalStatus ='%s',occupation ='%s',relationship ='%s',race ='%s',sex ='%s',capitalGain ='%d',capitalLoss ='%d',hoursperweek ='%d',nativeCountry ='%s',salperyear ='%s')>" %(
    self.age, self.workclass,self.fnlwgt,self.education,self.educationNum,self.maritalStatus,self.occupation,self.relationship,self.race,self.sex,self.capitalGain,self.capitalLoss,self.hoursperweek,self.nativeCountry,self.salperyear)

# printing the table scheme 
#print(Adult.__table__)

# creating the Table in the Engine, i.e memory
Base.metadata.create_all(engine)

#binding the engine to the session 
SessionMaker = sessionmaker(bind=engine)

session = SessionMaker()

# adding the data in the session , by first converting first 5 records to dictionary and then accessing individiuallyusing addall to add multiple rows 

dict1 = (df.head().to_dict('index'))
for x in dict1.values():
    temp = Adult(**x)
    session.add(temp)
    
# Commit flushes all the new data in session to the Database in memmory 
session.commit()

# Query 1 : updating hoursperweek for 50 year old person

print("************ Query 1 *********** \n")

print("Records having  50 years aged  \n",'-'*80)
for adt in session.query(Adult).filter(Adult.age == 50):
    print(adt)
    print('-'*80)
   

# Updating The Hoursperweek for 50 years old
session.query(Adult).filter(Adult.age == 50).update({'hoursperweek' : 20})
session.commit()

print("After Updating hoursperweek to 20 and fetching records from DB \n",'-'*80)
for adt in session.query(Adult).filter(Adult.age == 50):
    print(adt)
    print('-'*80)

#***************************************************************************************
# Query 2 : updating workclass to private 

print("************ Query 2 *********** \n")

print("Checking if record exists where workclass is not Private \n",'-'*80)
for adt in session.query(Adult).filter(Adult.workclass != ' Private'):
    print(adt)
    print('-'*80)
    
session.query(Adult).filter(Adult.workclass != ' Private').update({'workclass' : ' Private'})
session.commit()

print("After Updating Workclass to Private and fetching from DB \n",'-'*80)
for adt in session.query(Adult).all():
    print(adt)
    print('-'*80)

In [ ]:
#******************************************************************************************************
#                         Task 3 :  To write two basic Delete Queries 
#
#******************************************************************************************************
#importing the packages and setting an alias pandas and all the sqlalchemy related functions 

import pandas as pd
import sqlalchemy as sqy
from sqlalchemy import  create_engine,Column,Integer,String,Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


#reading the dataSet 

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# List of Column Names from the Adultnames file
ColumnNames= ['age','workclass','fnlwgt','education','educationNum','maritalStatus','occupation','relationship','race','sex','capitalGain','capitalLoss','hoursperweek','nativeCountry','salperyear']

df.columns = ColumnNames

#printing the Data read
#print(df.head())

# Creating a sqlalchemy engine
engine = create_engine('sqlite:///:memory:', echo=False)
#print(sqy.__version__)

# Constructing the Base Class from declarative to create table from it 
Base = declarative_base() 

class Adult(Base):
    __tablename__ = 'adult'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    workclass = Column(String)
    fnlwgt = Column(Integer)
    education = Column(String)
    educationNum = Column(Integer)
    maritalStatus = Column(String)
    occupation = Column(String)
    relationship = Column(String)
    race = Column(String)
    sex = Column(String)
    capitalGain = Column(Integer)
    capitalLoss = Column(Integer)
    hoursperweek = Column(Integer)
    nativeCountry = Column(String)
    salperyear = Column(String)
   
    def __repr__(self):
        return "<Adult(age='%d', workclass='%s', fnlwgt='%d',education='%s', educationNum='%d',maritalStatus ='%s',occupation ='%s',relationship ='%s',race ='%s',sex ='%s',capitalGain ='%d',capitalLoss ='%d',hoursperweek ='%d',nativeCountry ='%s',salperyear ='%s')>" %(
    self.age, self.workclass,self.fnlwgt,self.education,self.educationNum,self.maritalStatus,self.occupation,self.relationship,self.race,self.sex,self.capitalGain,self.capitalLoss,self.hoursperweek,self.nativeCountry,self.salperyear)

# printing the table scheme 
#print(Adult.__table__)

# creating the Table in the Engine, i.e memory
Base.metadata.create_all(engine)

#binding the engine to the session 
SessionMaker = sessionmaker(bind=engine)

session = SessionMaker()

# adding the data in the session , by first converting first 5 records to dictionary and then accessing individiuallyusing addall to add multiple rows 

dict1 = (df.head().to_dict('index'))
for x in dict1.values():
    temp = Adult(**x)
    session.add(temp)
    
# Commit flushes all the new data in session to the Database in memmory 
session.commit()

#Task3: to write basic Delete queries
#********************************************************************
#Query 1 : To delete the record where workclass is not private 

print("************ Query 1 *********** \n")

print("Checking if record exists where workclass is not Private \n",'-'*80)
for adt in session.query(Adult).filter(Adult.workclass != ' Private'):
    print(adt)
    print('-'*80)
    
session.query(Adult).filter(Adult.workclass != ' Private').delete()
session.commit()

print("After Deleting and fetching from DB , check if  record now exists \n",'-'*80)
for adt in session.query(Adult).all():
    print(adt)
    print('-'*80)

#********************************************************************
#Query 2 : To delete the record where workclass is not private 

print("************ Query 2 *********** \n")
print("Checking if record exists where education Number is other than 13 \n",'-'*80)
for adt in session.query(Adult).filter(Adult.educationNum == 13).all():
    print(adt)
    print('-'*80)
    
session.query(Adult).filter(Adult.educationNum == 13).delete()
session.commit()

print("After Deleting the record , fetching from DB , if filtered record exists \n",'-'*80)
for adt in session.query(Adult).all():
    print(adt)
    print('-'*80)

#**************************************************************************

In [ ]:
#******************************************************************************************************
#                         Task 4 :  To write two filter Queries 
#
#******************************************************************************************************
#importing the packages and setting an alias pandas and all the sqlalchemy related functions 

import pandas as pd
import sqlalchemy as sqy
from sqlalchemy import  create_engine,Column,Integer,String,Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


#reading the dataSet 

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# List of Column Names from the Adultnames file
ColumnNames= ['age','workclass','fnlwgt','education','educationNum','maritalStatus','occupation','relationship','race','sex','capitalGain','capitalLoss','hoursperweek','nativeCountry','salperyear']

df.columns = ColumnNames

#printing the Data read
#print(df.head())

# Creating a sqlalchemy engine
engine = create_engine('sqlite:///:memory:', echo=False)
#print(sqy.__version__)

# Constructing the Base Class from declarative to create table from it 
Base = declarative_base() 

class Adult(Base):
    __tablename__ = 'adult'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    workclass = Column(String)
    fnlwgt = Column(Integer)
    education = Column(String)
    educationNum = Column(Integer)
    maritalStatus = Column(String)
    occupation = Column(String)
    relationship = Column(String)
    race = Column(String)
    sex = Column(String)
    capitalGain = Column(Integer)
    capitalLoss = Column(Integer)
    hoursperweek = Column(Integer)
    nativeCountry = Column(String)
    salperyear = Column(String)
   
    def __repr__(self):
        return "<Adult(age='%d', workclass='%s', fnlwgt='%d',education='%s', educationNum='%d',maritalStatus ='%s',occupation ='%s',relationship ='%s',race ='%s',sex ='%s',capitalGain ='%d',capitalLoss ='%d',hoursperweek ='%d',nativeCountry ='%s',salperyear ='%s')>" %(
    self.age, self.workclass,self.fnlwgt,self.education,self.educationNum,self.maritalStatus,self.occupation,self.relationship,self.race,self.sex,self.capitalGain,self.capitalLoss,self.hoursperweek,self.nativeCountry,self.salperyear)

# printing the table scheme 
#print(Adult.__table__)

# creating the Table in the Engine, i.e memory
Base.metadata.create_all(engine)

#binding the engine to the session 
SessionMaker = sessionmaker(bind=engine)

session = SessionMaker()

# adding the data in the session , by first converting first 5 records to dictionary and then accessing individiuallyusing addall to add multiple rows 

dict1 = (df.head().to_dict('index'))
for x in dict1.values():
    temp = Adult(**x)
    session.add(temp)
    
# Commit flushes all the new data in session to the Database in memmory 
session.commit()

#Task4: to write Filter queries

print("************ Query 1 *********** \n")
#********************************************************************
#Query 1 : To get all the people who have done masters 


print("To See those who have studied till masters  \n",'-'*80)
for adt in session.query(Adult).filter(Adult.education.like('%Masters%')):
    print(adt)
    print('-'*80)
    

#********************************************************************
#Query 2 : To see gender distribution by Country 

print("************ Query 2 *********** \n")

print("To See how many people have studied masters \n",'-'*80)
#print(session.query(Adult).filter(Adult.nativeCountry.like('%United-States%')).group_by(Adult.sex).count(Adult.sex))
print(session.query(Adult).filter(Adult.education.like('%Masters%')).count())

print('-'*80)
    

#**************************************************************************

In [ ]:
#******************************************************************************************************
#                         Task 5 :  To write two Func Queries 
#
#******************************************************************************************************
#importing the packages and setting an alias pandas and all the sqlalchemy related functions 

import pandas as pd
import sqlalchemy as sqy
from sqlalchemy import  create_engine,Column,Integer,String,Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


#reading the dataSet 

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')

# List of Column Names from the Adultnames file
ColumnNames= ['age','workclass','fnlwgt','education','educationNum','maritalStatus','occupation','relationship','race','sex','capitalGain','capitalLoss','hoursperweek','nativeCountry','salperyear']

df.columns = ColumnNames

#printing the Data read
#print(df.head())

# Creating a sqlalchemy engine
engine = create_engine('sqlite:///:memory:', echo=False)
#print(sqy.__version__)

# Constructing the Base Class from declarative to create table from it 
Base = declarative_base() 

class Adult(Base):
    __tablename__ = 'adult'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    workclass = Column(String)
    fnlwgt = Column(Integer)
    education = Column(String)
    educationNum = Column(Integer)
    maritalStatus = Column(String)
    occupation = Column(String)
    relationship = Column(String)
    race = Column(String)
    sex = Column(String)
    capitalGain = Column(Integer)
    capitalLoss = Column(Integer)
    hoursperweek = Column(Integer)
    nativeCountry = Column(String)
    salperyear = Column(String)
   
    def __repr__(self):
        return "<Adult(age='%d', workclass='%s', fnlwgt='%d',education='%s', educationNum='%d',maritalStatus ='%s',occupation ='%s',relationship ='%s',race ='%s',sex ='%s',capitalGain ='%d',capitalLoss ='%d',hoursperweek ='%d',nativeCountry ='%s',salperyear ='%s')>" %(
    self.age, self.workclass,self.fnlwgt,self.education,self.educationNum,self.maritalStatus,self.occupation,self.relationship,self.race,self.sex,self.capitalGain,self.capitalLoss,self.hoursperweek,self.nativeCountry,self.salperyear)

# printing the table scheme 
#print(Adult.__table__)

# creating the Table in the Engine, i.e memory
Base.metadata.create_all(engine)

#binding the engine to the session 
SessionMaker = sessionmaker(bind=engine)

session = SessionMaker()

# adding the data in the session , by first converting first 5 records to dictionary and then accessing individiuallyusing addall to add multiple rows 

dict1 = (df.head().to_dict('index'))
for x in dict1.values():
    temp = Adult(**x)
    session.add(temp)
    
# Commit flushes all the new data in session to the Database in memmory 
session.commit()

#Task5: to write func queries
#********************************************************************
from sqlalchemy import func

print("************ Query 1 *********** \n")

#Query 1 : To get gender distribution for country 

print("To show the gender distribution for country  \n",'-'*80)
print(session.query(Adult.nativeCountry,Adult.sex,func.count('*')).group_by(Adult.nativeCountry,Adult.sex).all())
print('-'*80)
    

#********************************************************************
#Query 2 : To see how many are married 

print("************ Query 2 *********** \n")

print("To See how many people are married \n",'-'*80)
print(session.query(Adult.maritalStatus,func.count('*')).group_by(Adult.maritalStatus).all())

print('-'*80)
    

#**************************************************************************